Repository kedro-org/kedro-viz, pull requests merged in 2019-11, with the labels that each got.

#74 Allow chart to resize with parent container
  src/components/flowchart/index.js
Labels: Type: Enhancement

#75 Fix SVG import issues
  src/components/icon-toolbar/index.js
  src/components/icon-toolbar/label-icon.svg
  src/components/icon-toolbar/theme-icon.svg
  src/components/icons/label.js
  src/components/icons/menu.js
  src/components/icons/theme.js
  src/components/sidebar/index.js
  src/components/sidebar/menu-icon.svg
  src/components/sidebar/sidebar.test.js
Labels: Type: Fix

#76 Add data-id attributes on nodes and edges
  src/components/flowchart/draw.js
Labels: Type: Feature

#78 Add python-dateutil==2.8.0 to unblock release
  package/requirements.txt
Labels: Type: Fix

#77 3.0.1
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
  package/requirements.txt
  src/components/flowchart/draw.js
  src/components/flowchart/index.js
  src/components/icon-toolbar/index.js
  src/components/icon-toolbar/label-icon.svg
  src/components/icon-toolbar/theme-icon.svg
  src/components/icons/label.js
  src/components/icons/menu.js
  src/components/icons/theme.js
  src/components/sidebar/index.js
  src/components/sidebar/menu-icon.svg
  src/components/sidebar/sidebar.test.js
Labels: Type: Release

#79 FIX links on npmjs.org
  README.md
Labels: Type: Documentation, Type: Fix

#80 [KED-1218] Add App props to specify theme and hide theme/label icon buttons
  RELEASE.md
  src/components/app/index.js
  src/components/app/load-data.js
  src/components/app/load-data.test.js
  src/components/icon-toolbar/icon-toolbar.test.js
  src/components/icon-toolbar/index.js
  src/reducers/reducers.test.js
  src/utils/data/animals.mock.js
  src/utils/data/demo.mock.js
  src/utils/data/lorem-ipsum.mock.js
  src/utils/random-data.js
Labels: Type: Feature
