Repository kedro-org/kedro-viz, pull requests merged in 2019-07, with the labels that each got.

#10 [KED-786] Fix zoom offset
  src/components/flowchart/index.js
Labels: Type: Fix

#11 [KED-866] Fix minor Readme issues
  .github/img/pipeline_visualisation.png
  README.md
Labels: Type: Fix

#12 Run tests, linter, build & lib before npm publish
  package.json
Labels: Type: Enhancement

#14 Add instruction to access from another machine
  README.md
Labels: Type: Documentation

#15 Add CODEOWNERS file
  CODEOWNERS
  licenses.json
Labels: Type: Enhancement

#2 [KED-824] Adopt a new JSON format
  package/features/steps/cli_steps.py
  package/kedro_viz/server.py
  package/tests/test_server.py
Labels: Type: Enhancement

#8 [KED-824][KED-788] Use new JSON API in app, and calculate transitive links on the fly
  .gitignore
  CONTRIBUTING.md
  README.md
  src/actions/actions.test.js
  src/components/app/app.test.js
  src/components/app/index.js
  src/components/app/load-data.js
  src/components/chart-ui/chart-ui.test.js
  src/components/description/description.test.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/linked-nodes.js
  src/components/flowchart/linked-nodes.test.js
  src/components/history/history.test.js
  src/components/node-list/node-list.scss
  src/components/node-list/node-list.test.js
  src/components/sidebar-tabs/sidebar-tabs.test.js
  src/components/tag-list/tag-list.test.js
  src/components/wrapper/wrapper.test.js
  src/config.js
  src/index.js
  src/reducers/index.js
  src/reducers/reducers.test.js
  src/selectors/edges.js
  src/selectors/edges.test.js
  src/selectors/index.test.js
  src/selectors/layout.test.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/selectors/tags.test.js
  src/utils/data.mock.js
  src/utils/format-data.js
  src/utils/index.js
  src/utils/random-data.js
  src/utils/state.mock.js
  src/utils/utils.test.js
Labels: Type: Enhancement

#22 Fix path animations
  package-lock.json
  package.json
  src/components/flowchart/index.js
Labels: Type: Enhancement

#18 Fix Python version missing badge
  README.md
Labels: Type: Documentation

#19 Add Appveyor CI config
  Makefile
  README.md
  RELEASE.md
  appveyor.yml
Labels: Type: Enhancement

#24 Pin pip version to be less than 19.2
  package/features/environment.py
Labels: Type: Fix

#25 Unpin pip version
  package/features/environment.py
  package/features/steps/cli_steps.py
Labels: Type: Fix

#20 [KED-812] Toggle linked-node active state on click
  .babelrc
  .circleci/config.yml
  package-lock.json
  package.json
  src/actions/index.js
  src/components/flowchart/flowchart.scss
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/flowchart/linked-nodes.js
  src/components/flowchart/linked-nodes.test.js
  src/components/flowchart/styles/_edges.scss
  src/components/flowchart/styles/_node-icon.scss
  src/components/flowchart/styles/_node-text.scss
  src/components/flowchart/styles/_tooltip.scss
  src/components/flowchart/styles/_variables.scss
  src/components/flowchart/styles/flowchart.scss
  src/reducers/index.js
  src/reducers/reducers.test.js
  src/selectors/edges.js
  src/selectors/edges.test.js
  src/selectors/index.js
  src/selectors/index.test.js
  src/selectors/linked-nodes.js
  src/selectors/linked-nodes.test.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/styles/_variables.scss
  src/utils/format-data.js
Labels: Type: Enhancement, Type: Feature
