Repository kedro-org/kedro-viz, pull requests merged in 2020-12, with the labels that each got.

#318 [KED-2204] Add support for production `kedro viz` backend
  package.json
Labels: Type: Enhancement

#322 [KED-2184] Add 'private' flag prop
  src/config.js
  src/utils/flags.js
  src/utils/flags.test.js
Labels: Type: Feature

#328 Add graceful fallback response for API calls
  src/store/load-data.js
Labels: Type: Enhancement, Type: Fix

#295 [KED-2166] Add additional fields to meta data panel
  src/components/metadata/index.js
  src/components/metadata/metadata-list.js
  src/components/metadata/metadata-row.js
  src/components/metadata/metadata-value.js
  src/components/metadata/metadata.test.js
  src/components/metadata/styles/metadata.scss
  src/selectors/metadata.js
Labels: Type: Feature

#333 [KED-2166] Remove meta flag
  README.md
  src/actions/nodes.js
  src/actions/nodes.test.js
  src/config.js
  src/selectors/metadata.js
Labels: Type: Feature

#307 [KED-1923] Add LazyList component using IntersectionObserver on sidebar
  README.md
  src/components/lazy-list/index.js
  src/components/lazy-list/lazy-list.test.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-group.test.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-row-list.js
  src/components/node-list/node-list-row.js
  src/components/node-list/styles/_group.scss
  src/components/node-list/styles/_row.scss
  src/config.js
  src/selectors/linked-nodes.js
  src/utils/index.js
  tools/test-lib/react-app/app.test.js
Labels: Type: Enhancement

#325 Update Kedro-UI to v1.1.4 & implement relevant changes
  package-lock.json
  package.json
  src/actions/check-font-loaded.js
  src/actions/check-font-loaded.test.js
  src/components/app/index.js
  src/components/pipeline-list/index.js
  src/components/pipeline-list/pipeline-list.scss
  src/components/pipeline-list/pipeline-list.test.js
  src/utils/state.mock.js
Labels: Type: Enhancement

#335 Fix flags list in readme
  README.md
Labels: Type: Documentation, Type: Fix

#336 3.8.0
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#337 Disable internal CSS in exported SVGs to fix error
  src/components/export-modal/export-graph.js
Labels: Type: Fix

#340 3.8.1
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release
