Repository kedro-org/kedro-viz, pull requests merged in 2020-10, with the labels that each got.

#273 [KED-2135]Fix side-effects in prepareState caused by pipeline flag setup
  src/config.js
  src/utils/state.mock.js
Labels: Type: Fix

#274 [KED-1941]Remove isParam and schema_id from Kedro-Viz store
  src/components/app/app.test.js
  src/components/app/index.js
  src/store/normalize-data.js
  src/utils/data/animals.mock.js
  src/utils/data/demo.mock.js
Labels: Type: Enhancement

#236 [KED-1887] Sidebar update
  package.json
  src/components/app/app.scss
  src/components/flowchart/styles/_layers.scss
  src/components/flowchart/styles/_node.scss
  src/components/icon-button/icon-button.scss
  src/components/icon-button/icon-button.test.js
  src/components/icon-button/index.js
  src/components/icons/indicator-off.js
  src/components/icons/indicator-partial.js
  src/components/icons/indicator.js
  src/components/icons/map.js
  src/components/icons/minus.js
  src/components/icons/node-icon.js
  src/components/icons/plus.js
  src/components/minimap-toolbar/index.js
  src/components/minimap-toolbar/minimap-toolbar.scss
  src/components/minimap-toolbar/minimap-toolbar.test.js
  src/components/node-list/filter-nodes.js
  src/components/node-list/filter-nodes.test.js
  src/components/node-list/index.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-group.test.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-items.js
  src/components/node-list/node-list-items.test.js
  src/components/node-list/node-list-row.js
  src/components/node-list/node-list-row.test.js
  src/components/node-list/node-list-search.js
  src/components/node-list/node-list-toggle.js
  src/components/node-list/node-list-toggle.test.js
  src/components/node-list/node-list.js
  src/components/node-list/node-list.test.js
  src/components/node-list/styles/_filter.scss
  src/components/node-list/styles/_group.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_search.scss
  src/components/node-list/styles/_section.scss
  src/components/node-list/styles/_toggle.scss
  src/components/node-list/styles/_variables.scss
  src/components/node-list/styles/node-list.scss
  src/components/primary-toolbar/index.js
  src/components/primary-toolbar/primary-toolbar.test.js
  src/components/sidebar/index.js
  src/components/tag-list/index.js
  src/components/tag-list/tag-list.scss
  src/components/tag-list/tag-list.test.js
  src/config.js
  src/selectors/disabled.js
  src/styles/_variables.scss
  tools/test-lib/react-app/app.test.js
Labels: Type: Enhancement, Type: Feature

#275 [KED-2035] Expose parameter metadata
  RELEASE.md
  package/kedro_viz/server.py
  package/tests/input.json
  package/tests/result.json
  package/tests/test_server.py
Labels: hacktoberfest-accepted

#277 [KED-1696] Drop Kedro 0.14.* support
  RELEASE.md
  package/features/environment.py
  package/features/viz.feature
  package/kedro_viz/server.py
  package/requirements.txt
  package/tests/test_server.py
Labels: hacktoberfest-accepted

#280 [KED-2179] Hide random seed message unless using random data
  src/utils/random-data.js
  src/utils/random-utils.js
  src/utils/random-utils.test.js
Labels: Type: Fix

#278 Improve lib-test docs
  CONTRIBUTING.md
Labels: Type: Documentation

#270 [KED-1979] Retrieve modular pipeline data asynchronously from different endpoints
  src/actions/actions.test.js
  src/actions/graph.test.js
  src/actions/index.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/components/app/app.test.js
  src/components/app/index.js
  src/components/icons/loading.scss
  src/components/pipeline-list/index.js
  src/components/pipeline-list/pipeline-list.test.js
  src/components/wrapper/index.js
  src/components/wrapper/wrapper.test.js
  src/config.js
  src/config.test.js
  src/index.js
  src/reducers/graph.js
  src/reducers/index.js
  src/reducers/loading.js
  src/reducers/nodes.js
  src/reducers/pipeline.js
  src/reducers/reducers.test.js
  src/selectors/loading.js
  src/selectors/nodes.test.js
  src/selectors/pipeline.js
  src/selectors/pipeline.test.js
  src/store/__mocks__/load-data.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/store/load-data.js
  src/store/normalize-data.js
  src/store/normalize-data.test.js
  src/utils/index.js
  src/utils/state.mock.js
  src/utils/utils.test.js
Labels: Type: Feature, hacktoberfest-accepted

#281 [KED-2174] Update Python unit tests using the same json file as front-end's
  package/tests/input.json
  package/tests/test-data.json
  package/tests/test-format.json
  package/tests/test_server.py
Labels: hacktoberfest-accepted

#285 [KED-2172] Rename pipeline.default to pipeline.main in state
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/components/pipeline-list/pipeline-list.test.js
  src/store/initial-state.js
  src/store/normalize-data.js
Labels: Type: Enhancement

#283 [KED-2187] Fix heading order
  src/components/node-list/node-list-groups.js
  src/components/node-list/styles/_row.scss
  src/components/wrapper/index.js
  src/components/wrapper/wrapper.scss
Labels: Type: Fix

#288 Fix chart rendering edge cases and hover styles
  src/components/app/app.scss
  src/components/flowchart/draw.js
  src/components/icon-button/icon-button.scss
Labels: Type: Fix

#289 Hotfix: Fix pipelines flag default
  src/config.js
Labels: Type: Fix

#287 3.6.0
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#279 [KED-2099] Use the same JSON mock data files for JS+Python end unit/e2e tests
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/actions/actions.test.js
  src/components/app/app.test.js
  src/components/node-list/node-list-items.test.js
  src/reducers/reducers.test.js
  src/selectors/linked-nodes.test.js
  src/selectors/pipeline.test.js
  src/store/__mocks__/load-data.js
  src/store/initial-state.test.js
  src/store/normalize-data.test.js
  src/utils/data-source.js
  src/utils/data-source.test.js
  src/utils/data/animals.mock.js
  src/utils/data/animals.mock.json
  src/utils/data/input.json
  src/utils/state.mock.js
  tools/test-lib/react-app/app.js
Labels: Issue: Feature Request

#286 [KED-2160] Style the new pipeline selection dropdown
  src/components/node-list/index.js
  src/components/node-list/node-list-group.test.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-items.test.js
  src/components/node-list/node-list-search.js
  src/components/node-list/node-list.js
  src/components/node-list/node-list.test.js
  src/components/node-list/styles/_group.scss
  src/components/node-list/styles/_search.scss
  src/components/node-list/styles/node-list.scss
  src/components/pipeline-list/index.js
  src/components/pipeline-list/pipeline-list.scss
  src/components/pipeline-list/pipeline-list.test.js
  src/components/sidebar/index.js
  src/components/sidebar/sidebar.scss
  src/styles/_variables.scss
  tools/test-lib/react-app/app.test.js
Labels: Type: Enhancement

#290 [KED-2189] SVG rendering performance
  src/components/flowchart/draw.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/icon.js
  src/components/flowchart/index.js
  src/components/flowchart/styles/_node.scss
  src/components/flowchart/styles/flowchart.scss
  src/components/icons/node-icon.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
Labels: Type: Enhancement

#292 [KED-2222] Don't run eslint against .json files on pre-commit
  package.json
Labels: Type: Fix

#276 [KED-1423] Feature/metadata panel
  src/components/flowchart/index.js
  src/components/icon-button/index.js
  src/components/icons/close.js
  src/components/icons/copy.js
  src/components/icons/node-icon.js
  src/components/metadata/index.js
  src/components/metadata/metadata-list.js
  src/components/metadata/metadata-row.js
  src/components/metadata/metadata-value.js
  src/components/metadata/metadata.test.js
  src/components/metadata/styles/metadata.scss
  src/components/sidebar/sidebar.scss
  src/components/wrapper/index.js
  src/config.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/selectors/metadata.js
  src/selectors/nodes.js
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/utils/graph/graph.js
  src/utils/modifiers.js
  src/utils/modifiers.test.js
Labels: Type: Feature
