Repository kedro-org/kedro-viz, pull requests merged in 2020-11, with the labels that each got.

#296 [KED-2186] Hide graph when loading+switching to new pipeline
  src/actions/pipelines.js
  src/actions/pipelines.test.js
Labels: Type: Enhancement

#294 [KED-2181] Deprecate pipelines flag
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/components/sidebar/index.js
  src/config.js
  src/selectors/pipeline.js
  src/selectors/pipeline.test.js
  src/store/initial-state.test.js
Labels: Type: Enhancement

#297 [KED-2253] Fix pipeline selector flicker when switching pipelines
  src/actions/graph.js
  src/actions/graph.test.js
  src/actions/index.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/flowchart/styles/flowchart.scss
  src/components/pipeline-list/index.js
  src/components/pipeline-list/pipeline-list.scss
  src/components/pipeline-list/pipeline-list.test.js
  src/reducers/visible.js
  src/store/initial-state.js
Labels: Type: Enhancement, Type: Fix

#303 Update flags docs
  README.md
  src/config.js
Labels: Type: Documentation

#302 HOTFIX: Fix sidebar height bug in Safari
  src/components/node-list/styles/node-list.scss
Labels: Type: Fix

#300 3.7.0
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#293 [KED-2180] retrieve node metadata asynchronously from different endpoints
  package-lock.json
  package.json
  src/actions/nodes.js
  src/actions/nodes.test.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/node-list/index.js
  src/reducers/loading.js
  src/reducers/nodes.js
  src/reducers/reducers.test.js
  src/selectors/loading.js
  src/store/__mocks__/load-data.js
  src/store/initial-state.js
  src/store/load-data.js
  src/store/normalize-data.js
  src/utils/data/node_data.mock.json
  src/utils/data/node_parameters.mock.json
  src/utils/data/node_task.mock.json
  src/utils/index.js
  src/utils/utils.test.js
Labels: Type: Feature

#308 [KED-2293] Add batching to tag actions
  src/actions/actions.test.js
  src/actions/index.js
  src/actions/tags.js
  src/components/node-list/index.js
  src/reducers/reducers.test.js
  src/reducers/tags.js
  src/selectors/tags.test.js
Labels: Type: Enhancement

#313 [KED-2307] Disable Python 3.6/3.7 jobs in daily CI workflow
  .circleci/config.yml
Labels: Type: Fix

#301 [KED-2134] Use CSS custom property for theme colours
  src/components/app/app.scss
  src/components/flowchart/styles/_edges.scss
  src/components/flowchart/styles/_layers.scss
  src/components/flowchart/styles/_node.scss
  src/components/flowchart/styles/_variables.scss
  src/components/flowchart/styles/flowchart.scss
  src/components/icon-button/icon-button.scss
  src/components/icons/loading.scss
  src/components/metadata/styles/metadata.scss
  src/components/minimap-toolbar/minimap-toolbar.scss
  src/components/minimap/styles/_node.scss
  src/components/minimap/styles/_variables.scss
  src/components/minimap/styles/minimap.scss
  src/components/node-list/styles/_filter.scss
  src/components/node-list/styles/_group.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_search.scss
  src/components/node-list/styles/_section.scss
  src/components/node-list/styles/_toggle.scss
  src/components/node-list/styles/node-list.scss
  src/components/pipeline-list/pipeline-list.scss
  src/components/sidebar/sidebar.scss
  src/components/tooltip/tooltip.scss
  src/components/wrapper/wrapper.scss
  src/styles/_extends.scss
  src/styles/_mixins.scss
  src/styles/_variables.scss
Labels: Type: Enhancement

#317 Reduce missed clicks on the flowchart
  src/components/flowchart/styles/flowchart.scss
Labels: Type: Fix

#319 Fix CSS custom properties
  src/components/node-list/styles/_variables.scss
  src/components/node-list/styles/node-list.scss
Labels: Type: Fix
