Repository kedro-org/kedro-viz, pull requests merged in 2020-09, with the labels that each got.

#253 [KED-2024] Fix visible.layers bug and refactor layer visibility state
  src/components/app/app.test.js
  src/components/app/index.js
  src/components/export-modal/export-modal.test.js
  src/components/flowchart/draw.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/icon-toolbar/icon-toolbar.test.js
  src/components/icon-toolbar/index.js
  src/components/primary-toolbar/index.js
  src/components/primary-toolbar/primary-toolbar.test.js
  src/reducers/index.js
  src/reducers/layers.js
  src/reducers/reducers.test.js
  src/selectors/disabled.js
  src/selectors/disabled.test.js
  src/selectors/layers.js
  src/selectors/layout.js
  src/selectors/ranks.js
  src/selectors/ranks.test.js
  src/store/index.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/store/normalize-data.js
  src/utils/graph/index.js
Labels: Type: Enhancement, Type: Fix

#254 [KED-2034] Put multi-pipeline selector behind a flag
  README.md
  src/components/sidebar/index.js
  src/components/sidebar/sidebar.test.js
  src/config.js
  src/store/initial-state.js
  src/utils/state.mock.js
Labels: Type: Feature

#259 Add a note about file extensions in the docs
  CONTRIBUTING.md
Labels: Type: Documentation

#261 [KED-2037] Focus search-bar with Cmd+F/Ctrl+F
  package-lock.json
  package.json
  src/components/node-list/node-list-search.js
  src/components/node-list/node-list-search.test.js
  src/setupTests.js
Labels: Type: Feature

#264 Fix prepublishOnly task
  package.json
Labels: Type: Fix

#267 3.5.1
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#268 [KED-1857] Refactor and optimise flowchart performance
  src/components/flowchart/draw.js
  src/components/flowchart/index.js
  src/components/flowchart/styles/_node.scss
Labels: Type: Enhancement

#269 [KED-1857] Fix interrupted chart transitions
  src/components/flowchart/draw.js
Labels: Type: Fix

#271 Fix bug caused by typo in saveStateToLocalStorage
  src/store/index.js
Labels: Type: Fix
