Repository kedro-org/kedro-viz, pull requests merged in 2020-06, with the labels that each got.

#182 Fix tooltip triangle styling issues
  src/components/easter-egg/easter-egg.scss
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/tooltip/tooltip.scss
Labels: Type: Fix

#178 [KED-1657] Seed randomly-generated data with UUIDs
  package-lock.json
  package.json
  src/utils/index.js
  src/utils/random-data.js
  src/utils/random-utils.js
  src/utils/random-utils.test.js
  src/utils/utils.test.js
  trufflehog-ignore.txt
Labels: Type: Enhancement

#181 Update readme/contributing docs
  CONTRIBUTING.md
  README.md
Labels: Type: Documentation

#186 [KED-1730] Improve rendering performance
  src/actions/check-font-loaded.test.js
  src/components/wrapper/index.js
  src/components/wrapper/wrapper.test.js
  src/selectors/layers.js
  src/selectors/layout.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/utils/state.mock.js
Labels: Type: Enhancement

#188 [KED-1745] Autoformat viz python code using black
  Makefile
  package/.isort.cfg
  package/features/steps/cli_steps.py
  package/kedro_viz/server.py
  package/test_requirements.txt
  package/tests/test_server.py
Labels: python

#197 Fix random seeding
  src/utils/random-data.js
  src/utils/random-utils.js
Labels: Type: Fix

#195 3.3.1
  .circleci/config.yml
  .github/img/pipeline_visualisation.png
  CONTRIBUTING.md
  Makefile
  README.md
  RELEASE.md
  package-lock.json
  package.json
  package/.isort.cfg
  package/features/steps/cli_steps.py
  package/kedro_viz/__init__.py
  package/kedro_viz/server.py
  package/requirements.txt
  package/test_requirements.txt
  package/tests/test_server.py
  src/actions/check-font-loaded.test.js
  src/components/easter-egg/easter-egg.scss
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/tooltip/tooltip.scss
  src/components/wrapper/index.js
  src/components/wrapper/wrapper.test.js
  src/selectors/layers.js
  src/selectors/layout.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/utils/index.js
  src/utils/random-data.js
  src/utils/random-utils.js
  src/utils/random-utils.test.js
  src/utils/state.mock.js
  src/utils/utils.test.js
  trufflehog-ignore.txt
Labels: Type: Release

#198 [KED-1790] Add layers to demo data
  src/utils/data/demo.mock.js
Labels: Type: Enhancement

#199 [KED-1807] Update SSH key fingerprint in CircleCI config
  .circleci/config.yml
Labels: Type: Fix

#185 [KED-1650] New graphing algorithm & feature flags
  COPYING.txt
  README.md
  package-lock.json
  package.json
  src/actions/actions.test.js
  src/actions/index.js
  src/components/app/app.test.js
  src/components/app/index.js
  src/config.js
  src/reducers/flags.js
  src/reducers/index.js
  src/reducers/reducers.test.js
  src/selectors/flags.js
  src/selectors/flags.test.js
  src/selectors/layers.js
  src/selectors/layers.test.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/store/index.js
  src/store/initial-state.js
  src/utils/flags.js
  src/utils/flags.test.js
  src/utils/graph/common.js
  src/utils/graph/graph.test.js
  src/utils/graph/index.js
  src/utils/graph/layout.js
  src/utils/graph/routing.js
  src/utils/graph/solver.js
Labels: Type: Enhancement

#200 [KED-1809] Consolidate mock datasets and delete unnecessary ones
  CONTRIBUTING.md
  src/actions/check-font-loaded.test.js
  src/components/app/app.test.js
  src/components/app/index.js
  src/components/export-modal/export-modal.test.js
  src/components/flowchart/flowchart.test.js
  src/components/icon-toolbar/icon-toolbar.test.js
  src/components/node-list/filter-nodes.test.js
  src/components/node-list/node-list-group.test.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-row.test.js
  src/components/node-list/node-list-search.test.js
  src/components/node-list/node-list.test.js
  src/components/sidebar/sidebar.test.js
  src/components/tag-list/tag-list.test.js
  src/components/wrapper/wrapper.test.js
  src/reducers/reducers.test.js
  src/selectors/disabled.test.js
  src/selectors/edges.test.js
  src/selectors/layers.test.js
  src/selectors/layout.test.js
  src/selectors/nodes.test.js
  src/selectors/ranks.test.js
  src/selectors/tags.test.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/utils/data-source.js
  src/utils/data-source.test.js
  src/utils/data/animals.mock.js
  src/utils/data/layers.mock.js
  src/utils/data/lorem-ipsum.mock.js
  src/utils/graph/graph.test.js
  src/utils/state.mock.js
Labels: Type: Enhancement

#187 [KED-1650] Improve random generator variations
  src/utils/random-data.js
Labels: Type: Enhancement

#201 Protect URL constructor/searchParams where browser support is limited.
  src/utils/flags.js
  src/utils/random-utils.js
Labels: Type: Fix

#202 3.4.0
  .circleci/config.yml
  CONTRIBUTING.md
  COPYING.txt
  README.md
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
  src/actions/actions.test.js
  src/actions/check-font-loaded.test.js
  src/actions/index.js
  src/components/app/app.test.js
  src/components/app/index.js
  src/components/export-modal/export-modal.test.js
  src/components/flowchart/flowchart.test.js
  src/components/icon-toolbar/icon-toolbar.test.js
  src/components/node-list/filter-nodes.test.js
  src/components/node-list/node-list-group.test.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-row.test.js
  src/components/node-list/node-list-search.test.js
  src/components/node-list/node-list.test.js
  src/components/sidebar/sidebar.test.js
  src/components/tag-list/tag-list.test.js
  src/components/wrapper/wrapper.test.js
  src/config.js
  src/reducers/flags.js
  src/reducers/index.js
  src/reducers/reducers.test.js
  src/selectors/disabled.test.js
  src/selectors/edges.test.js
  src/selectors/flags.js
  src/selectors/flags.test.js
  src/selectors/layers.js
  src/selectors/layers.test.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/selectors/nodes.test.js
  src/selectors/ranks.test.js
  src/selectors/tags.test.js
  src/store/index.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/utils/data-source.js
  src/utils/data-source.test.js
  src/utils/data/animals.mock.js
  src/utils/data/demo.mock.js
  src/utils/data/layers.mock.js
  src/utils/data/lorem-ipsum.mock.js
  src/utils/flags.js
  src/utils/flags.test.js
  src/utils/graph/common.js
  src/utils/graph/graph.test.js
  src/utils/graph/index.js
  src/utils/graph/layout.js
  src/utils/graph/routing.js
  src/utils/graph/solver.js
  src/utils/random-data.js
  src/utils/random-utils.js
  src/utils/state.mock.js
Labels: Type: Release
