Repository kedro-org/kedro-viz, pull requests merged in 2020-02, with the labels that each got.

#96 [KED-1046] Redesign sidebar list to group nodes by type
  package-lock.json
  package.json
  src/actions/actions.test.js
  src/actions/index.js
  src/components/app/index.js
  src/components/app/initial-state.js
  src/components/app/initial-state.test.js
  src/components/app/load-data.js
  src/components/chart-ui/chart-ui.scss
  src/components/chart-ui/chart-ui.test.js
  src/components/chart-ui/index.js
  src/components/easter-egg/easter-egg.test.js
  src/components/easter-egg/index.js
  src/components/flowchart/flowchart.test.js
  src/components/node-list/index.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-group.test.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-item.js
  src/components/node-list/node-list-item.test.js
  src/components/node-list/node-list-toggle.js
  src/components/node-list/node-list.scss
  src/components/node-list/node-list.test.js
  src/components/sidebar/index.js
  src/components/sidebar/sidebar.scss
  src/reducers/index.js
  src/reducers/reducers.test.js
  src/selectors/edges.test.js
  src/selectors/node-types.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/store/index.js
  src/utils/format-data.js
  src/utils/index.js
Labels: Type: Feature

#46 [KED-1336] Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  RELEASE.md
Labels: Type: Documentation

#103 Lint and format Sass (especially CSS declaration order) with stylelint
  .prettierrc
  .stylelintignore
  .stylelintrc
  package-lock.json
  package.json
  src/components/easter-egg/easter-egg.scss
  src/components/flowchart/styles/_tooltip.scss
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/node-list/node-list.scss
  src/components/sidebar/sidebar.scss
  src/components/tag-list/tag-list.scss
  src/components/wrapper/wrapper.scss
  src/styles/_mixins.scss
Labels: Type: Enhancement

#93 [KED-1196] Add --pipeline flag to visualize non-default Kedro pipeline
  RELEASE.md
  package/features/environment.py
  package/features/steps/cli_steps.py
  package/features/viz.feature
  package/kedro_viz/server.py
  package/requirements.txt
  package/tests/test_server.py
Labels: Type: Feature

#98 [KED-1315] Add secret scan CircleCI step
  .circleci/config.yml
  Makefile
  package/test_requirements.txt
  trufflehog-ignore.txt
Labels: Type: Infosec

#108 [KED-1373] Fix CircleCI memory errors when running Jest JS tests
  .circleci/config.yml
  package.json
Labels: Type: Fix

#107 Improve test coverage
  src/components/easter-egg/easter-egg.test.js
  src/components/easter-egg/index.js
Labels: Type: Enhancement

#104 Use mocker instead of mock in Python unit tests
  package/tests/test_server.py
Labels: Type: Enhancement

#105 [KED-1291] Update README to mention all available CLI options
  README.md
  RELEASE.md
Labels: Type: Documentation

#110 Add "upcoming release" header back in RELEASE.md
  RELEASE.md
Labels: Type: Documentation

#111 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Documentation

#106 [KED-1374] Refactor store
  src/actions/check-font-loaded.js
  src/actions/check-font-loaded.test.js
  src/components/app/index.js
  src/components/app/initial-state.js
  src/components/app/initial-state.test.js
  src/components/app/load-data.js
  src/components/app/load-data.test.js
  src/components/icon-toolbar/icon-toolbar.test.js
  src/components/node-list/node-list-groups.js
  src/components/sidebar/sidebar.test.js
  src/reducers/reducers.test.js
  src/store/helpers.js
  src/store/index.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/store/load-data.js
  src/store/load-data.test.js
  src/store/normalize-data.js
  src/utils/index.js
  src/utils/state.mock.js
Labels: Type: Enhancement

#113 [KED-1318] Refactor reducers
  src/components/flowchart/flowchart.test.js
  src/reducers/index.js
  src/reducers/node-type.js
  src/reducers/nodes.js
  src/reducers/reducers.test.js
  src/reducers/tags.js
  src/selectors/edges.js
  src/selectors/edges.test.js
  src/selectors/layout.js
  src/selectors/linked-nodes.js
  src/selectors/node-types.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/selectors/tags.js
  src/selectors/tags.test.js
  src/store/index.js
  src/store/initial-state.js
  src/store/normalize-data.js
Labels: Type: Enhancement

#116 [KED-1410] Update codeowners file
  .github/CODEOWNERS
Labels: Type: Enhancement

#115 [KED-1407] Refactor actions, splitting them into multiple files
  src/actions/actions.test.js
  src/actions/index.js
  src/actions/node-type.js
  src/actions/nodes.js
  src/actions/tags.js
  src/components/flowchart/index.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-item.js
  src/components/node-list/node-list-toggle.js
  src/components/tag-list/index.js
  src/reducers/node-type.js
  src/reducers/nodes.js
  src/reducers/reducers.test.js
  src/reducers/tags.js
  src/selectors/edges.test.js
  src/selectors/linked-nodes.test.js
  src/selectors/nodes.test.js
Labels: Type: Enhancement

#117 [KED-1347] Fix PNG exports
  src/components/icon-toolbar/export-modal.js
  src/components/icon-toolbar/export-modal.test.js
Labels: Type: Fix
