Repository kedro-org/kedro-viz, pull requests merged in 2020-08, with the labels that each got.

#222 [KED-1883] Add automated testing for npm package import
  .babelrc
  .circleci/config.yml
  .gitignore
  CONTRIBUTING.md
  package.json
  tools/test-lib/react-app/__mocks__/fileMock.js
  tools/test-lib/react-app/__mocks__/styleMock.js
  tools/test-lib/react-app/app.js
  tools/test-lib/react-app/app.test.js
  tools/test-lib/react-app/babel.config.js
  tools/test-lib/react-app/index.js
  tools/test-lib/react-app/package-lock.json
  tools/test-lib/react-app/package.json
  tools/test-lib/react-app/webpack.config.js
  tools/test-lib/serve.js
  tools/test-lib/setup.js
  trufflehog-ignore.txt
Labels: Type: Feature

#235 Improve performance of `getLinkedNodes`
  src/selectors/linked-nodes.js
Labels: Type: Enhancement

#220 [KED-1926] Refactor initial state setup, and store disabled nodes in localStorage
  package-lock.json
  package.json
  src/components/app/app.test.js
  src/components/app/index.js
  src/store/helpers.js
  src/store/index.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/store/normalize-data.js
  src/store/normalize-data.test.js
Labels: Type: Enhancement

#247 [KED-1991] Add more tests for minimap, flowchart and minimap-toolbar
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/minimap-toolbar/minimap-toolbar.test.js
  src/components/minimap/index.js
  src/components/minimap/minimap.test.js
Labels: Type: Enhancement

#248 [KED-1872] Rename master branch to main and deprecate develop
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  src/utils/data/demo.mock.js
  tools/versioning.py
Labels: Type: Enhancement

#249 Fix mispelling in demo dataset
  src/utils/data/demo.mock.js
Labels: Type: Fix

#250 Delete duplicate icon-button component
  src/components/icon-button/index.js
  src/components/icon-toolbar/icon-button.js
  src/components/icon-toolbar/icon-button.test.js
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/icon-toolbar/index.js
  src/components/minimap-toolbar/minimap-toolbar.scss
  src/components/sidebar/sidebar.scss
Labels: Type: Fix

#251 Reduce toolbar-button height on smaller screens
  src/components/icon-button/icon-button.scss
  src/components/minimap-toolbar/minimap-toolbar.scss
Labels: Type: Fix
