Repository kedro-org/kedro-viz, pull requests merged in 2020-05, with the labels that each got.

#155 [KED-1586] Add node selected state, and improve node active/selected styling
  src/components/flowchart/draw.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/flowchart/styles/_node.scss
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-row.js
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_variables.scss
  src/reducers/nodes.js
  src/reducers/reducers.test.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
Labels: Type: Enhancement, Type: Fix

#161 [KED-1647] Refactor random data generator, and add layers
  src/config.js
  src/utils/index.js
  src/utils/random-data.js
  src/utils/utils.test.js
Labels: Type: Enhancement

#158 [KED-1518] Wrap tooltip names & invert tooltip in top half of screen
  src/components/flowchart/index.js
  src/components/flowchart/styles/_tooltip.scss
  src/components/flowchart/styles/_variables.scss
  src/components/flowchart/styles/flowchart.scss
  src/components/tooltip/index.js
  src/components/tooltip/tooltip.scss
  src/components/tooltip/tooltip.test.js
Labels: Type: Enhancement, Type: Fix

#162 [KED-1645] Add node-list-count to node-list group headings
  src/components/node-list/node-list-group.js
  src/components/node-list/styles/_row.scss
  src/selectors/node-types.js
Labels: Type: Enhancement, Type: Feature

#163 [KED-1658] Refactor config.js & move random-data import
  src/components/app/app.test.js
  src/config.js
  src/config.test.js
  src/index.js
  src/store/helpers.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/store/load-data.js
  src/utils/data-source.js
  src/utils/data-source.test.js
Labels: Type: Enhancement

#164 Make node-list group toggle button point right when collapsed
  src/components/node-list/styles/_group.scss
Labels: Type: Enhancement

#167 [KED-1421] Add icon stack column to right edge of the main sidebar
  src/actions/actions.test.js
  src/actions/index.js
  src/components/export-modal/export-graph.js
  src/components/export-modal/export-graph.test.js
  src/components/export-modal/export-modal.scss
  src/components/export-modal/export-modal.test.js
  src/components/export-modal/index.js
  src/components/icon-toolbar/export-modal.test.js
  src/components/icon-toolbar/icon-button.js
  src/components/icon-toolbar/icon-button.test.js
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/icon-toolbar/icon-toolbar.test.js
  src/components/icon-toolbar/index.js
  src/components/icons/menu.js
  src/components/node-list/node-list-toggle.js
  src/components/node-list/styles/_group.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_search.scss
  src/components/node-list/styles/_toggle.scss
  src/components/node-list/styles/node-list.scss
  src/components/sidebar/index.js
  src/components/sidebar/menu-buttons.js
  src/components/sidebar/sidebar.scss
  src/components/sidebar/sidebar.test.js
  src/components/tooltip/tooltip.scss
  src/components/tooltip/tooltip.test.js
  src/components/wrapper/index.js
  src/config.js
  src/reducers/visible.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/store/initial-state.js
  src/styles/_extends.scss
  src/styles/_variables.scss
Labels: Type: Enhancement, Type: Feature, Type: Fix

#166 Remove the need to transition layer height on zoom
  src/components/flowchart/index.js
  src/components/flowchart/styles/_layers.scss
Labels: Type: Enhancement

#169 [KED-1638] Update colour scheme, improve print/export styles
  src/components/export-modal/export-graph.js
  src/components/flowchart/draw.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/icon.js
  src/components/flowchart/index.js
  src/components/flowchart/styles/_edges.scss
  src/components/flowchart/styles/_layers.scss
  src/components/flowchart/styles/_node.scss
  src/components/flowchart/styles/_variables.scss
  src/components/flowchart/styles/flowchart.scss
  src/components/icon-toolbar/icon-toolbar.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_search.scss
  src/components/node-list/styles/_toggle.scss
  src/components/node-list/styles/_variables.scss
  src/components/sidebar/sidebar.scss
  src/components/tag-list/tag-list.scss
  src/components/tooltip/tooltip.scss
  src/components/wrapper/wrapper.scss
  src/config.js
  src/selectors/nodes.js
  src/styles/_extends.scss
  src/styles/_variables.scss
Labels: Type: Enhancement

#171 Deselect nodes on Escape key, and when already selected
  src/components/node-list/node-list-groups.js
Labels: Type: Enhancement

#174 Increase zoom/pan extent and change prepublish test script
  package.json
  src/components/flowchart/index.js
Labels: Type: Enhancement

#177 [KED-1594] Replace pipeline visualisation
  .github/img/pipeline_visualisation.png
  README.md
Labels: Type: Documentation
