Repository kedro-org/kedro-viz, pull requests merged in 2021-04, with the labels that each got.

#398 [KED-2365] Simplify layout algorithm, improve layout quality and performance
  src/utils/graph/constraints.js
  src/utils/graph/graph.js
  src/utils/graph/graph.test.js
  src/utils/graph/layout.js
  src/utils/graph/solver.js
Labels: Type: Enhancement

#407 [KED-2528] Improve layer solving approach when layers partially defined
  src/utils/graph/graph.js
  src/utils/graph/layout.js
  src/utils/graph/solver.js
Labels: Type: Enhancement

#415 [KED 2535] - Delete lazy flag
  README.md
  src/components/flowchart/draw.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/minimap/draw.js
  src/components/minimap/index.js
  src/components/minimap/minimap.test.js
  src/components/node-list/node-list-row-list.js
  src/config.js
  src/selectors/linked-nodes.js
Labels: Type: Enhancement

#423 3.11.0
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#419 Restore snyk-protect on npm prepare
  .snyk
  package-lock.json
  package.json
  tools/test-lib/setup.js
Labels: Type: Fix

#426 [KED-2530] Add details about testing approach in style guide
  STYLE_GUIDE.md
Labels: Type: Documentation

#422 Add test to ensure legacy dataset support
  src/components/app/app.test.js
Labels: Type: Enhancement

#417 [KED-2593] Set sidebar visibility default to false on mobile
  src/config.js
  src/store/initial-state.js
Labels: Type: Feature
