Repository kedro-org/kedro-viz, pull requests merged in 2021-02, with the labels that each got.

#356 [KED-2381] Improve responsive zoom approach
  src/components/flowchart/index.js
  src/config.js
  src/selectors/layout.js
  src/selectors/layout.test.js
Labels: Type: Enhancement

#362 Fix node-list-row line-height regression
  src/components/node-list/styles/_row-label.scss
Labels: Type: Fix

#365 [KED-2210] Update circleci node version to 14.15
  .circleci/config.yml
Labels: Type: Enhancement

#364 [KED-2210] Update npm dependencies, especially D3
  package-lock.json
  package.json
  src/components/flowchart/draw.js
  src/components/flowchart/index.js
  src/components/minimap/index.js
Labels: Type: Enhancement

#366 [KED-2210] Repeatedly attempt dependency installs on CircleCI
  .circleci/config.yml
  tools/ci.js
Labels: Type: Fix

#363 [KED-2381] Refactor zoom and views
  package-lock.json
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/minimap/index.js
  src/components/minimap/minimap.test.js
  src/utils/view.js
  src/utils/view.test.js
Labels: Type: Enhancement

#367 [KED-2409] Update docs to remind on compatibility of Kedro-Viz 3.8.0 with Kedro 0.17
  CONTRIBUTING.md
  README.md
  RELEASE.md
Labels: Type: Documentation

#347 [KED-2212] Improve graph layout code quality, performance and docs
  src/utils/graph/common.js
  src/utils/graph/constraints.js
  src/utils/graph/graph.test.js
  src/utils/graph/layout.js
  src/utils/graph/solver.js
Labels: Type: Enhancement

#346 [KED-2328] Add code panel
  package-lock.json
  package.json
  src/actions/index.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/metadata/index.js
  src/components/metadata/metadata-code-toggle.js
  src/components/metadata/metadata-code.js
  src/components/metadata/metadata-code.test.js
  src/components/metadata/metadata-list.js
  src/components/metadata/styles/metadata-code-themes.scss
  src/components/metadata/styles/metadata-code.scss
  src/components/metadata/styles/metadata.scss
  src/components/sidebar/sidebar.scss
  src/config.js
  src/reducers/visible.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/store/initial-state.js
  src/styles/_variables.scss
Labels: Type: Feature

#370 [KED-2437] Fix minimum zoom level
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/minimap/index.js
Labels: Type: Fix

#372 Add note about 'code' flag to readme
  README.md
Labels: Type: Documentation

#373 [KED-2447] Fix node hover zoom bug
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
Labels: Type: Fix

#374 [KED-2448] Improve node selected view panning behaviour
  src/components/flowchart/index.js
  src/utils/view.js
  src/utils/view.test.js
Labels: Type: Enhancement

#371 3.9.0
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#361 Display warnings on large graphs
  src/actions/actions.test.js
  src/actions/index.js
  src/components/flowchart/flowchart.test.js
  src/components/large-pipeline-warning/index.js
  src/components/large-pipeline-warning/large-pipeline-warning.scss
  src/components/large-pipeline-warning/large-pipeline-warning.test.js
  src/components/wrapper/index.js
  src/config.js
  src/reducers/index.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/selectors/loading.js
  src/store/initial-state.js
  src/utils/state.mock.js
Labels: Type: Feature

#377 [KED-2453] Update large pipeline warning copy
  src/components/large-pipeline-warning/index.js
  src/components/large-pipeline-warning/large-pipeline-warning.scss
Labels: Type: Enhancement

#376 [KED-2446] Add new 'sizewarning' flag
  README.md
  src/config.js
  src/selectors/layout.js
  src/selectors/layout.test.js
Labels: Type: Enhancement, Type: Feature

#378 [KED-2466] Add stylelint 'rule-empty-line-before': 'always'
  .stylelintrc
  src/components/easter-egg/easter-egg.scss
  src/components/icons/loading.scss
  src/styles/_mixins.scss
Labels: Type: Enhancement

#379 Add Container component to simplify app/lib entrypoint
  src/components/app/index.js
  src/components/container/container.scss
  src/components/container/index.js
  src/index.js
Labels: Type: Enhancement

#380 Clean up SCSS tech debt
  src/components/app/app.scss
  src/components/export-modal/export-modal.scss
  src/components/export-modal/export-modal.test.js
  src/components/export-modal/index.js
  src/components/icon-button/icon-button.scss
  src/components/wrapper/index.js
  src/components/wrapper/wrapper.scss
  src/styles/_extends.scss
  src/styles/_mixins.scss
Labels: Type: Enhancement
