Repository kedro-org/kedro-viz, pull requests merged in 2021-03, with the labels that each got.

#381 [KED-2471] Add "Don't show this again" message to large-pipeline-warning
  src/components/large-pipeline-warning/index.js
  src/components/large-pipeline-warning/large-pipeline-warning.scss
  src/components/large-pipeline-warning/large-pipeline-warning.test.js
  src/config.js
Labels: Type: Enhancement, Type: Feature

#384 3.10.0
  RELEASE.md
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#386 3.10.1
  package-lock.json
  package.json
  package/kedro_viz/__init__.py
Labels: Type: Release

#387 Delete unused input.json test data
  src/utils/data/input.json
Labels: Type: Enhancement

#368 [KED-1591] Cite Kedro-Viz
  README.md
Labels: Priority: Low, Type: Documentation

#396 Remove 'id' reducer prop
  src/reducers/index.js
Labels: Type: Enhancement

#382 [KED-2163] Add architecture doc
  .github/img/app-architecture-data-flow.png
  .github/img/app-architecture-entry-points.png
  .github/img/app-architecture.png
  ARCHITECTURE.md
  CONTRIBUTING.md
Labels: Type: Documentation

#397 [KED-2367] Add metadata to random data generator
  src/actions/nodes.js
  src/actions/pipelines.js
  src/actions/pipelines.test.js
  src/components/metadata/metadata-code.js
  src/components/pipeline-list/index.js
  src/reducers/index.js
  src/selectors/pipeline.js
  src/store/normalize-data.js
  src/store/normalize-data.test.js
  src/utils/data-source.js
  src/utils/random-data.js
Labels: Type: Enhancement, Type: Feature

#375 [KED-2413] Add a style-guide document
  STYLE_GUIDE.md
Labels: Type: Documentation

#406 [KED-2534] Remove the code panel flag
  CODE_OF_CONDUCT.md
  README.md
  src/components/metadata/index.js
  src/config.js
Labels: Type: Enhancement

#403 [KED-2533] Fix/delete description from metadata
  package/kedro_viz/server.py
  package/tests/test_server.py
  src/components/metadata/metadata.test.js
  src/reducers/nodes.js
  src/reducers/reducers.test.js
  src/selectors/metadata.js
  src/store/normalize-data.js
  src/utils/data/node_task.mock.json
  src/utils/random-data.js
Labels: Type: Enhancement
