Repository kedro-org/kedro-viz, pull requests merged in 2021-05, with the labels that each got.

#418 Add JS variable naming section to style guide
  STYLE_GUIDE.md
Labels: Type: Documentation

#424 [KED-2521] - Highlighting parameters on the flowchart
  README.md
  src/actions/actions.test.js
  src/actions/index.js
  src/components/flowchart/draw.js
  src/components/flowchart/flowchart.test.js
  src/components/flowchart/index.js
  src/components/flowchart/styles/_edges.scss
  src/components/flowchart/styles/_node.scss
  src/components/flowchart/styles/_variables.scss
  src/components/metadata/metadata.test.js
  src/components/minimap/minimap.test.js
  src/components/node-list/index.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list.js
  src/config.js
  src/reducers/index.js
  src/reducers/reducers.test.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/store/normalize-data.js
  src/utils/state.mock.js
Labels: Type: Feature

#429 Refactor node list selectors and modular pipeline config
  src/components/node-list/index.js
  src/components/node-list/node-list-items.js
  src/components/node-list/node-list-items.test.js
  src/components/node-list/node-list.test.js
  src/config.js
Labels: Type: Enhancement, Type: Fix

#430 Expand/collapse modular pipelines on the graph - Part 1
  src/actions/modular-pipelines.js
  src/components/flowchart/draw.js
  src/components/icons/node-icon.js
  src/components/node-list/index.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-items.js
  src/components/node-list/node-list-row-list.js
  src/components/node-list/node-list-row.js
  src/components/node-list/node-list.js
  src/components/node-list/styles/_row.scss
  src/reducers/index.js
  src/reducers/modular-pipelines.js
  src/selectors/disabled.js
  src/selectors/edges.js
  src/selectors/metadata.js
  src/selectors/modular-pipelines.js
  src/selectors/nodes.js
  src/store/index.js
  src/store/normalize-data.js
  src/styles/_mixins.scss
Labels: Type: Feature

#436 [KED-2529] Layout engine docs
  ARCHITECTURE.md
  LAYOUT_ENGINE.md
  src/utils/graph/constraints.js
  src/utils/graph/graph.js
  src/utils/graph/graph.test.js
  src/utils/graph/solver.js
  trufflehog-ignore.txt
Labels: Type: Documentation

#448 [KED-2633] Add split panel component and implement into sidebar
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-items.js
  src/components/node-list/node-list-items.test.js
  src/components/node-list/node-list.js
  src/components/node-list/node-list.test.js
  src/components/node-list/styles/_panels.scss
  src/components/node-list/styles/_section.scss
  src/components/node-list/styles/node-list.scss
  src/components/split-panel/index.js
  src/components/split-panel/split-panel.test.js
Labels: Type: Enhancement

#446 Improve test coverage
  src/actions/actions.test.js
  src/components/container/container.test.js
  src/components/large-pipeline-warning/large-pipeline-warning.test.js
  src/reducers/reducers.test.js
Labels: Type: Enhancement

#453 Expand/collapse modular pipelines on the graph - Part 2
  src/components/icons/collapse.js
  src/components/icons/expand.js
  src/components/node-list/node-list-row.js
  src/components/node-list/styles/_row-label.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_variables.scss
  src/components/primary-toolbar/index.js
  src/selectors/contracted.js
  src/selectors/disabled.js
  src/selectors/edges.js
  src/selectors/layers.js
  src/selectors/layout.js
  src/selectors/linked-nodes.js
  src/selectors/modular-pipelines.js
  src/selectors/nodes.js
  src/selectors/pipeline.js
  src/selectors/ranks.js
Labels: Type: Feature
