Repository kedro-org/kedro-viz, pull requests merged in 2021-07, with the labels that each got.

#489 [KED-2690] Fix : Remove old graph
  ARCHITECTURE.md
  README.md
  package-lock.json
  package.json
  src/actions/graph.js
  src/actions/graph.test.js
  src/config.js
  src/selectors/layout.js
  src/selectors/layout.test.js
  src/selectors/metadata.js
  src/store/initial-state.test.js
  src/utils/graph/index.js
  src/utils/state.mock.js
Labels: Type: Fix

#454 [KED-2642] Filter panel updates and refactoring
  src/actions/actions.test.js
  src/actions/node-type.js
  src/components/node-list/index.js
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-groups.js
  src/components/node-list/node-list-groups.test.js
  src/components/node-list/node-list-items.js
  src/components/node-list/node-list-items.test.js
  src/components/node-list/node-list-row-list.js
  src/components/node-list/node-list-row.js
  src/components/node-list/node-list-row.test.js
  src/components/node-list/node-list-tree-item.js
  src/components/node-list/node-list.js
  src/components/node-list/node-list.test.js
  src/components/node-list/styles/_group.scss
  src/components/node-list/styles/_panels.scss
  src/components/node-list/styles/_row-label.scss
  src/components/node-list/styles/_row-toggle.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/_search.scss
  src/components/node-list/styles/_section.scss
  src/components/node-list/styles/_variables.scss
  src/components/node-list/styles/node-list.scss
  src/config.js
  src/reducers/node-type.js
  src/reducers/reducers.test.js
  src/selectors/node-types.js
  src/selectors/tags.js
  src/selectors/tags.test.js
  src/store/initial-state.js
Labels: Type: Feature

#508 Remove `modularpipelines` flag and fix capitalisation
  README.md
  RELEASE.md
Labels: Type: Documentation

#478 [KED-2681] Implement settings panel for flags
  package-lock.json
  package.json
  src/actions/actions.test.js
  src/actions/index.js
  src/components/app/index.js
  src/components/export-modal/export-modal.test.js
  src/components/icons/settings.js
  src/components/metadata/index.js
  src/components/metadata/metadata-code-toggle.js
  src/components/metadata/metadata-code.test.js
  src/components/metadata/metadata.test.js
  src/components/metadata/styles/metadata-code.scss
  src/components/primary-toolbar/index.js
  src/components/primary-toolbar/primary-toolbar.test.js
  src/components/settings-modal/index.js
  src/components/settings-modal/settings-modal.scss
  src/components/settings-modal/settings-modal.test.js
  src/components/toggle/index.js
  src/components/toggle/toggle.scss
  src/components/toggle/toggle.test.js
  src/components/wrapper/index.js
  src/config.js
  src/reducers/reducers.test.js
  src/reducers/visible.js
  src/store/index.js
  src/store/initial-state.js
  src/store/initial-state.test.js
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/utils/flags.js
  src/utils/flags.test.js
Labels: Type: Feature
