Repository kedro-org/kedro-viz, pull requests merged in 2021-01, with the labels that each got.

#339 Update SVG-Crowbar to fix errors
  package-lock.json
  package.json
  src/components/export-modal/export-graph.js
Labels: Type: Fix

#344 Fix icon-button tooltips on mobile
  src/components/icon-button/icon-button.scss
  src/components/minimap/index.js
  src/components/sidebar/sidebar.scss
Labels: Type: Fix

#343 [KED-2212] Improve graph performance
  src/utils/graph/common.js
  src/utils/graph/constraints.js
  src/utils/graph/graph.test.js
  src/utils/graph/layout.js
  src/utils/graph/solver.js
Labels: Type: Enhancement

#351 Fix sidebar border/box-shadow CSS rules
  src/styles/_extends.scss
Labels: Type: Fix

#349 [KED-2331] Fix missing indicators Chrome zoom bug
  src/components/icons/indicator-off.js
Labels: Type: Fix

#357 Update iconography
  src/components/app/app.scss
  src/components/icons/close.js
  src/components/icons/copy.js
  src/components/icons/indicator-off.js
  src/components/icons/indicator-partial.js
  src/components/icons/indicator.js
  src/components/icons/invisible.js
  src/components/icons/label.js
  src/components/icons/layers.js
  src/components/icons/map.js
  src/components/icons/minus.js
  src/components/icons/node-icon.js
  src/components/icons/plus.js
  src/components/icons/reset.js
  src/components/icons/theme.js
  src/components/icons/visible.js
Labels: Type: Enhancement

#355 Fix node-list-row keyboard focus states
  src/components/node-list/node-list-group.js
  src/components/node-list/node-list-row-list.js
  src/components/node-list/node-list-row.js
  src/components/node-list/styles/_filter.scss
  src/components/node-list/styles/_row.scss
Labels: Type: Fix

#359 [KED-2384] Update visibility icons to ensure visual alignment on toggle
  src/components/icons/invisible.js
  src/components/icons/visible.js
Labels: Type: Fix

#358 [KED-2385] Refactor row toggle/label CSS, and fix row hover icon bug
  src/components/node-list/node-list-items.js
  src/components/node-list/node-list.test.js
  src/components/node-list/styles/_filter.scss
  src/components/node-list/styles/_row-label.scss
  src/components/node-list/styles/_row-toggle.scss
  src/components/node-list/styles/_row.scss
  src/components/node-list/styles/node-list.scss
Labels: Type: Enhancement, Type: Fix
