Repository kedro-org/kedro-viz, pull requests merged in 2023-10, with the labels that each got.

#1563 Fix: Setting Env. Variable for cross platform
  package.json
Labels: Javascript

#1591 Remove old variable in `conf.py` now CSS has moved
  docs/source/conf.py
Labels: Type: Documentation

#1581 Remove writing to SQLite in Experiment Tracking (Frontend)
  cypress/tests/ui/experiment-tracking/experiment-tracking.cy.js
  cypress/tests/ui/experiment-tracking/menu.cy.js
  cypress/tests/ui/experiment-tracking/panel.cy.js
  package-lock.json
  src/actions/index.js
  src/apollo/mutations.js
  src/apollo/queries.js
  src/components/experiment-tracking/experiment-primary-toolbar/experiment-primary-toolbar.js
  src/components/experiment-tracking/run-details-modal/run-details-modal.js
  src/components/experiment-tracking/run-details-modal/run-details-modal.test.js
  src/components/experiment-tracking/run-export-modal/run-export-modal.js
  src/components/experiment-tracking/run-export-modal/run-export-modal.test.js
  src/components/experiment-tracking/run-metadata/run-metadata.js
  src/components/experiment-tracking/run-metadata/run-metadata.test.js
  src/components/experiment-tracking/runs-list-card/runs-list-card.js
  src/components/experiment-tracking/runs-list-card/runs-list-card.test.js
  src/components/experiment-tracking/runs-list/runs-list.js
  src/components/experiment-tracking/runs-list/runs-list.test.js
  src/components/experiment-wrapper/experiment-wrapper.js
  src/config.js
  src/reducers/index.js
  src/reducers/runs-metadata.js
  src/store/initial-state.js
  src/store/store.js
Labels: Javascript

#1590 Update demo project to use OmegaConfigLoader
  demo-project/README.md
  demo-project/conf/base/catalog_01_raw.yml
  demo-project/conf/base/catalog_02_int.yml
  demo-project/conf/base/catalog_03_prm.yml
  demo-project/conf/base/catalog_04_feature.yml
  demo-project/conf/base/catalog_05_model_input.yml
  demo-project/conf/base/catalog_06_models.yml
  demo-project/conf/base/catalog_08_reporting.yml
  demo-project/conf/base/catalog_09_tracking.yml
  demo-project/conf/base/catalog_globals.yml
  demo-project/conf/base/globals.yml
  demo-project/conf/base/parameters/feature_engineering.yml
  demo-project/conf/base/parameters/modelling.yml
  demo-project/conf/prod/catalog_globals.yml
  demo-project/conf/prod/globals.yml
  demo-project/pyproject.toml
  demo-project/src/demo_project/pipelines/reporting/nodes.py
  demo-project/src/demo_project/requirements.in
  demo-project/src/demo_project/settings.py
Labels: Python, Community
