Repository kedro-org/kedro-viz, pull requests merged in 2023-08, with the labels that each got.

#1489 Fix: Sidebar search width fix for longer text query
  RELEASE.md
  src/components/ui/search-bar/search-input/search-input.scss
Labels: Type: Bug

#1485 Fix for sidebar search result based on Pretty name flag
  RELEASE.md
  src/selectors/modular-pipelines.js
  src/selectors/nodes.js
  src/selectors/nodes.test.js
Labels: Type: Enhancement, Javascript

#1501 Fix README for PyPI
  README.md
Labels: Type: Documentation

#1509 Fix: Adding favicon to Kedro Demo
  RELEASE.md
  package/kedro_viz/api/apps.py
  package/tests/test_api/test_apps.py
Labels: Type: Bug, Python
