Repository kedro-org/kedro-viz, pull requests merged in 2024-04, with the labels that each got.

#1799 Extending stateful URLS with node filters and Expanding/collapsing modular pipelines flag
  RELEASE.md
  cypress/tests/ui/experiment-tracking/experiment-tracking.cy.js
  cypress/tests/ui/flowchart/flowchart.cy.js
  cypress/tests/ui/flowchart/menu.cy.js
  src/components/flowchart-wrapper/flowchart-wrapper.js
  src/components/node-list/index.js
  src/components/node-list/node-list.js
  src/components/node-list/node-list.test.js
  src/components/node-list/styles/_section.scss
  src/components/pipeline-list/pipeline-list.test.js
  src/components/settings-modal/settings-modal.js
  src/config.js
  src/store/initial-state.js
  src/store/normalize-data.js
  src/utils/get-key-by-value.js
  src/utils/get-key-by-value.test.js
  src/utils/hooks/use-generate-pathname.js
  src/utils/index.js
  src/utils/match-path.js
  src/utils/object-utils.js
  src/utils/object-utils.test.js
Labels: Javascript

#1846 CircleCI to Github actions migration for Kedro-Viz (test)
  .github/actions/install_kedro_and_python_dependencies/action.yml
  .github/actions/install_node_dependencies/action.yml
  .github/actions/setup_tests/action.yml
  .github/workflows/all-checks.yml
  .github/workflows/build-backend.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/javascript-lint-and-tests.yml
  .github/workflows/lint.yml
  .github/workflows/merge-gatekeeper.yml
  .github/workflows/unit-tests.yml
  trufflehog-ignore.txt
Labels: Enhancement

#1796 Refactor backend integration with Kedro by replacing bootstrap_project with configure_project
  RELEASE.md
  package/kedro_viz/integrations/kedro/data_loader.py
  package/kedro_viz/launchers/cli.py
  package/kedro_viz/launchers/jupyter.py
  package/kedro_viz/server.py
  package/tests/test_launchers/test_cli.py
  package/tests/test_launchers/test_jupyter.py
Labels: Enhancement, Python
